---
- name: Install Apache2 on Debian based OS
  apt: # Use the apt module
    name:
      - apache2 # package to install
      - apache2-utils
      - php
      - libapache2-mod-php
    state: present # check if already installed, if yes Ansible does nothing
    update_cache: yes # equivalent to run apt update command
  when: ansible_os_family == "Debian"

- name: Start Apache2 service if not started
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Enable mod_rewrite
  community.general.apache2_module:
    name: rewrite
    state: present
  notify: restart apache2