---
- name: Application deployment # Start new play
  hosts: all # Play will run on all hosts defined in the inventory
  gather_facts: yes
  become: true # Run the tasks with sudo/root
  tasks:
    - name: Main directory creation
      ansible.builtin.file:
        path: /var/www/myapp/
        state: directory
        mode:  "{{ mode }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      

    - name: Create subdirectories
      ansible.builtin.file:
        path: /var/www/myapp/{{ item }}
        state: directory
        mode:  "{{ mode }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      loop:
      - html
      - logs
      - config
    
    - name: Copy files from files folder
      ansible.builtin.template:
        src: ../templates/index.php.j2
        dest: /var/www/myapp/html/index.php
        mode: 0644
        owner: "{{ owner }}"
        group: "{{ group }}"
      notify: Reload Apache
    
    # This less robust
    #- name: Update Apache conf file
    #  ansible.builtin.lineinfile:
    #    path: /etc/apache2/sites-available/000-default.conf
    #    search_string: DocumentRoot /var/www/html
    #    line: DocumentRoot /var/www/myapp/html
    #   notify: Reload Apache 

    - name: Update Apache DocumentRoot to new app directory
      ansible.builtin.lineinfile:
        path: "{{ conf_apache_path }}"
        regexp: '^(\s*)DocumentRoot\s+.*'
        line: '    DocumentRoot /var/www/myapp/html'
        backup: true
      notify: Reload Apache
      
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded