---
- name: Application deployment # Start new play
  hosts: all # Play will run on all hosts defined in the inventory
  become: true # Run the tasks with sudo/root
  vars:
  tasks:
    - name: Main directory creation
      ansible.builtin.file:
        path: /var/www/myapp/
        state: directory
        mode:  "{{ mode }}"
        owner: "{{ owner }}"
        group: "{{ group }}"

    - name: Create subdirectories
      ansible.builtin.file:
        path: /var/www/myapp/{{ item }}
        state: directory
        mode:  "{{ mode }}"
        owner: "{{ owner }}"
        group: "{{ group }}"
      loop:
      - html
      - logs
      - config
    
    - name: Copy files from files folder
      ansible.builtin.copy:
        src: ./files/infos.php
        dest: /var/www/myapp/
        mode: 0644
        owner: "{{ owner }}"
        group: "{{ group }}"