---
- name: System preparation # Start new play
  hosts: all # Play will run on all hosts defined in the inventory
  become: true # Run the tasks with sudo/root
  #tasks:
  #  - include_tasks: ../tasks/deploy_web.yml
  roles:
    - ../roles/deploy_web